"""
Bug report compiler.

Phase 0: generates plain-text reports from Finding objects without calling Fireworks AI.
Phase 2: will call fireworks_client.generate_report_text() for polished markdown reports.

The separation is intentional and visible: this file calls Fireworks (Phase 2+),
vlm_client.py calls AMD vLLM. They are NEVER mixed.
"""

import logging
from sqlmodel import Session, select

from ..models import Finding, Report

logger = logging.getLogger(__name__)


async def compile_findings(run_id: int, db_session: Session) -> None:
    """
    For every Finding in this run that doesn't yet have a Report, generate one.
    Phase 0: plain-text summary (no Fireworks call).
    Phase 2: replace _generate_report_text() with fireworks_client call.
    """
    statement = select(Finding).where(Finding.run_id == run_id)
    findings = db_session.exec(statement).all()

    for finding in findings:
        # Skip if report already exists (idempotent)
        existing = db_session.exec(
            select(Report).where(Report.finding_id == finding.id)
        ).first()
        if existing:
            continue

        title = _make_title(finding.category, finding.severity)
        summary = finding.description
        repro_steps = _make_repro_steps(finding)
        raw_text = _assemble_markdown(finding, title, summary, repro_steps)

        report = Report(
            finding_id=finding.id,
            title=title,
            summary=summary,
            repro_steps=repro_steps,
            raw_text=raw_text,
        )
        db_session.add(report)
        logger.info("Report compiled for finding %d: %s", finding.id, title)

    db_session.commit()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_CAT_LABELS: dict[str, str] = {
    "broken_interaction": "Broken Interaction",
    "visual_layout": "Visual Layout Bug",
    "accessibility": "Accessibility Issue",
    "error_state": "Error State",
    "dead_link": "Dead Link",
    "other": "Bug",
}


def _make_title(category: str, severity: str) -> str:
    label = _CAT_LABELS.get(category, "Bug")
    return f"[{severity.upper()}] {label}"


def _make_repro_steps(finding: Finding) -> str:
    lines: list[str] = []

    trail = finding.action_trail
    if trail:
        lines.append("**Actions leading up to this finding:**")
        for action in trail[-5:]:
            lines.append(f"- {action}")
        lines.append("")

    lines.append(f"**Bug first observed at step {finding.step_num}.**")

    console = finding.console_errors
    if console:
        lines.append("")
        lines.append("**Console errors at time of discovery:**")
        for err in console[:5]:
            lines.append(f"- `{err}`")

    network = finding.network_errors
    if network:
        lines.append("")
        lines.append("**Network errors at time of discovery:**")
        for err in network[:5]:
            lines.append(f"- `{err}`")

    return "\n".join(lines)


def _assemble_markdown(
    finding: Finding,
    title: str,
    summary: str,
    repro_steps: str,
) -> str:
    console_block = (
        "\n".join(f"- `{e}`" for e in finding.console_errors[:5])
        or "_(none)_"
    )
    network_block = (
        "\n".join(f"- `{e}`" for e in finding.network_errors[:5])
        or "_(none)_"
    )

    return f"""# {title}

| Field | Value |
|-------|-------|
| **Severity** | {finding.severity} |
| **Category** | {finding.category} |
| **Step** | {finding.step_num} |
| **Finding ID** | {finding.id} |

## Summary

{summary}

## Reproduction Steps

{repro_steps}

## Console Errors

{console_block}

## Network Errors

{network_block}

---
*Report generated by Shadow QA Phase 0 compiler (plain-text mode — Fireworks wired in Phase 2)*
"""
